### ISSUE TITLE
FAQ Copy

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#46]
**Can I submit questions now?**
For sure. Just type your question into our “Ask the Expert” field above to let us know what you’d like to see covered!

**If I decide to donate, how do I do it?**
Kind of you to ask. You can donate by filling out the “Partner with Us” donation form found above! We accept all major credit cards, and Apple Pay for your convenience.

**Comment by 1stevengrant** [comment]
resolved

**Comment by joenicolette** [comment]
@1stevengrant Hmm...still don't see this updated. Maybe I'm missing something. :)

**Comment by 1stevengrant** [comment]
right enough @joenicolette - looks like my database thing didn't take. Sorted now.

**Comment by joenicolette** [comment]
😎
